# Generated by Django 6.0 on 2026-01-05 09:22

import authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', authentication.managers.CustomUserManager()),
            ],
        ),
    ]
